server:
  port: 10086
spring:
  rabbitmq:
    host: 47.102.113.59
    username: xiaoliu
    password: 123
    virtual-host: /xiaoliu
    #当遇到同样名字的时候，是否允许覆盖注册
    main:
      allow-bean-definition-overriding: true